### ISSUE TITLE
Create the flex banner designs for the day of the event

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2019-tasks#10]
We'd need following flex banner designs -

1. One main banner for the conference audi
2. Two banners for venue listing sponsors etc
3. Couple more vertical standees

**Comment by ananyo2012** [comment]
@inovizz We need to put the Exact dimensions of the banners and flexes. Can you co-ordinate with Abhinay on this ? You probably need to visit the venue over the weekend taking him to take the dimensions.

**Comment by inovizz** [comment]
Abhinay to take care.
