### ISSUE TITLE
Create an Emailer design for College ambassadors/Working Professionals to promote PyConf Hyd

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2019-tasks#13]
We'll be connecting with our college ambassadors in Hyderabad to promote PyConf Hyderabad in their colleges and also with working professionals in Hyderabad and nearby area.

So we need to come up with an Emailer Design with all possible information so that it can be used for promotions.

Content for the emailer -

Intro of PyConf Hyderabad -
PyConf Hyderabad, it is one of the premier conferences in Telangana and Andhra Pradesh on using and developing the Python programming language. It is conducted annually by the Python developer community and brings together the best Python developers, experts, academics, scientists and enthusiasts from all across the country.

- Date of the event - 7th & 8th December
- Venue - IIIT-Hyderabad
- Format of the event - 
   - 7th December - Workshops & DevSprints
   - 8th December - Conference
Website - https://pyconf.hydpy.org/2019/
Ticket URL - https://www.townscript.com/e/pyconf-hyderabad-2019
CFP URL - https://www.papercall.io/pyconf-hyderabad2019

Creativity is with the designer, but the above information can be used.

**Comment by snehithallamraju** [comment]
Do we have a list of possible information that we need to include in the email?

**Comment by inovizz** [comment]
Yes. Let me update the description. And it shall not be a text email but an email design image with graphics and text.

**Comment by inovizz** [comment]
![logo](https://user-images.githubusercontent.com/3849885/68051278-0f068b00-fd0d-11e9-8f0f-2c2d63cd12ac.png)
