### ISSUE TITLE
Check/Verify logistics at IIIT-Hyderabad 

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2019-tasks#15]
We need to check for IIIT-Hyderabad logistics, like

1. Projector
2. Mic
3. Extension boards connecting possibility
4. Laptop cords for presentation

**Comment by inovizz** [comment]
@GoelJatin - I would need your help here.

**Comment by ananyo2012** [comment]
Co-ordinate with Ranjith and Bobby on this.

**Comment by inovizz** [comment]
Sanchit and Manan to verify during last week of November.

**Comment by GoelJatin** [comment]
> @GoelJatin - I would need your help here.

Sure!!
