### ISSUE TITLE
Invite Upstream Project maintainers for DevSprint CFPs

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2019-tasks#19]
@ananyo2012 can you take this up and invite maintainers of following Upstream Projects for DevSprints -

1. scikit-learn - `@vinayak-mehta`
2. Pandas
3. Django
4. Pip - `@pradyunsg`
5. Ansible (check with RedHat folks) - `@trishnaguha` from RedHat
6. httpie
7. zulip - `@punchagan`
8. kivy - `@akshayaurora`
9. SecureDrop - Kushal

and feel free to add more and invite. I could think of these projects. It shall be good to have 4-5 projects.

**Comment by ananyo2012** [comment]
Sure Sanchit. I will work on it

**Comment by ananyo2012** [comment]
Pinged most of the mentors of projects mentioned above. Pandas and Django don't have Indian contributors as such. Also checked for Jupyter, Flask and few Docker projects. They don't have much Indian upstream contributors as well

**Comment by ananyo2012** [comment]
Please add any other projects as well

**Comment by inovizz** [comment]
For Pandas, check if Bhavani from Chennai can do that?

**Comment by GoelJatin** [comment]
Sent email to all members who submitted proposals for PyCon India 2019

**Comment by ananyo2012** [comment]
Thanks Jatin !

**Comment by ananyo2012** [comment]
This is the present status of mentors I approached - https://docs.google.com/spreadsheets/d/1EBcmN_QvDmxBm4k0I7I8l8SGoj6zV_YNxbH27ECsofU/edit?usp=sharing . Not much good going till now
