### ISSUE TITLE
Re-announce DevSprint CFPs as the first post didn't have an impact.

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2019-tasks#23]
@kyogesh - please plan to announce it day after tomorrow. Use the same flyer but please also announce it on mailing list.

**Comment by GoelJatin** [comment]
Did we announce Dev sprints on the mailing lists yet? Otherwise I can help here!!

**Comment by ananyo2012** [comment]
No, please send out the email in mailing list. We should also email Mentors
who submitted a Devsprint in PyCon India. Let's send to all of them as well.

**Comment by GoelJatin** [comment]
Do we have a list of the Mentors, can someone share that. Meanwhile I'm sending CFP for DevSprints on the mailing list.

**Comment by inovizz** [comment]
Send it on following mailing lists

HydPy
PyCon India
NCR Python
ChennaiPy
BangPypers

**Comment by ananyo2012** [comment]
I will update the mentor emails in DM by tonight

**Comment by GoelJatin** [comment]
Sent, waiting for moderator approval for some of them!!
