### ISSUE TITLE
Create flyer for speaker Announcement

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2019-tasks#28]
We'll be announcing two talk speakers in one post and one individual for a workshop. So basically we need 2 posters

1. Talk Speaker flyer (2 in 1)
2. Workshop speakers flyer

**Comment by ananyo2012** [comment]
@inovizz So we plan to announce all speakers in social media ?

**Comment by inovizz** [comment]
![speakers1](https://user-images.githubusercontent.com/3849885/69904940-8e05e680-13d3-11ea-8f07-9d4c6fe4ed4a.png)

**Comment by inovizz** [comment]
![speakers2](https://user-images.githubusercontent.com/3849885/69905045-96aaec80-13d4-11ea-9b9b-b35c1b4e05a1.png)

**Comment by inovizz** [comment]
![speakers3](https://user-images.githubusercontent.com/3849885/69905329-29995600-13d8-11ea-9463-1c4b26b0dbef.png)
![speakers4](https://user-images.githubusercontent.com/3849885/69905330-2d2cdd00-13d8-11ea-8be3-d5c2e59aa959.png)

**Comment by inovizz** [comment]
![speakers5](https://user-images.githubusercontent.com/3849885/69905423-3c605a80-13d9-11ea-90bc-e5ae80dadf36.png)
