### ISSUE TITLE
Create poster for days counter 

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2019-tasks#30]
We need to have 10 posters for conf counter: 10 to 1.

Starts on 27th Nov and ends on 6th Dec

**Comment by GoelJatin** [comment]
Hi @inovizz , can you or someone please create the posters. We'll make the SM announcements

CC: @kyogesh

**Comment by inovizz** [comment]
![10](https://user-images.githubusercontent.com/3849885/69621411-13506a80-1065-11ea-9bfc-ea0a4e2c1bde.png)

**Comment by inovizz** [comment]
Please make this announcement today before the talk schedule.

**Comment by inovizz** [comment]
![23](https://user-images.githubusercontent.com/3849885/69622089-4fd09600-1066-11ea-96e5-26b315094b4d.png)
![24](https://user-images.githubusercontent.com/3849885/69622091-50692c80-1066-11ea-8fe9-c8b04f652136.png)
![25](https://user-images.githubusercontent.com/3849885/69622093-50692c80-1066-11ea-83c8-8dbfda593508.png)
![26](https://user-images.githubusercontent.com/3849885/69622095-50692c80-1066-11ea-9f7d-d3b940a55d00.png)
![27](https://user-images.githubusercontent.com/3849885/69622096-5101c300-1066-11ea-8293-d46875bcd2bb.png)
![28](https://user-images.githubusercontent.com/3849885/69622097-5101c300-1066-11ea-874b-36f4ad4fe600.png)
![29](https://user-images.githubusercontent.com/3849885/69622099-5101c300-1066-11ea-89d9-3b192a75fe69.png)
![30](https://user-images.githubusercontent.com/3849885/69622101-519a5980-1066-11ea-914d-1f287ce4bd03.png)
![31](https://user-images.githubusercontent.com/3849885/69622102-519a5980-1066-11ea-9bca-cddf4cf149ca.png)

**Comment by GoelJatin** [comment]
Done!
