### ISSUE TITLE
Create poster for Regular tickets sold out

### ISSUE THREAD

**Issue by GoelJatin** [HydPy/pyconfhyd2019-tasks#34]
Last 5 Regular tickets left, we need to create a poster announcing tickets sold out

**Comment by inovizz** [comment]
![regular_ticket](https://user-images.githubusercontent.com/3849885/69622505-1187a680-1067-11ea-94dd-ee79e46afd60.png)

**Comment by ananyo2012** [comment]
And Late bird tickets open as well

**Comment by GoelJatin** [comment]
Announcement made on Twitter and Facebook
