### ISSUE TITLE
Announce Late Bird ticket sales

### ISSUE THREAD

**Issue by GoelJatin** [HydPy/pyconfhyd2019-tasks#35]
Create poster and announce late bird tickets sales

**Comment by GoelJatin** [comment]
@inovizz , need a poster for this one!!

**Comment by inovizz** [comment]
![25tickets](https://user-images.githubusercontent.com/3849885/69701147-47359980-1112-11ea-908d-0d4673b6da65.png)


lets do it this way - mention early bird ticket sales has started and the poster say 25 tickets left.

**Comment by GoelJatin** [comment]
Announcements made on Twitter and Facebook
