### ISSUE TITLE
Create sticker design for PyConf Hyderabad 2019

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2019-tasks#6]
We need a sticker design for PyConf Hyderabad 2019.

**Comment by bhansa** [comment]
We can have some round stickers with the below design:
<img src="https://user-images.githubusercontent.com/9723884/67311792-d650ff80-f51d-11e9-9ba8-804de9d4bf63.png" width="200" />

**Comment by bhansa** [comment]
@subuhani Please add your suggestions as well.

**Comment by ananyo2012** [comment]
And Hydpy Stcickers as well !

**Comment by inovizz** [comment]
Abhinay will take care of this as well.
